readme, textarea
nocsland/project_practice pull request #5
Opened 2023-12-09 17:18 UTC by nadejdasopilova

2023-12-09 18:11 UTC, nocsland requested changes
Пара неточностей. Необходимо исправить

2023-12-09 18:11 UTC, nocsland commented on PP1/summary_text/docs/README.md
> +Для удобства пользователя добавлен скрипт run.sh, который проверит активировано ли виртуальное окружение, в случае необходимости, создаст его и установит зависимости.
а также запустит само приложение.

2023-12-09 18:11 UTC, nocsland commented on PP1/summary_text/docs/README.md
>  2.	Выбрать одну из двух возможных кнопок «Ввод текста» или «Загрузка файла» и нажать кнопку «Генерировать»;
Кнопка называется теперь "Создать"

2023-12-09 18:42 UTC, nadejdasopilova commented on PP1/summary_text/docs/README.md
>  2.	Выбрать одну из двух возможных кнопок «Ввод текста» или «Загрузка файла» и нажать кнопку «Генерировать»;
Done

2023-12-09 18:42 UTC, nadejdasopilova commented on PP1/summary_text/docs/README.md
> +Для удобства пользователя добавлен скрипт run.sh, который проверит активировано ли виртуальное окружение, в случае необходимости, создаст его и установит зависимости.
Done

2023-12-09 19:02 UTC, nocsland commented on PP1/summary_text/src/summary_text.py
> +            text = st.text_area(label="Проверьте и при необходимости отредактируйте:", value=text)
Надо подумать. Может быть можно использовать text_area один раз, без дублирования кода.

2023-12-09 20:35 UTC, nocsland approved these changes

2023-12-09 20:52 UTC, nocsland requested changes
Я прочитал, начало файла и пожалуй его надо поправить, те цели и функционал что у нас в черновике убирать и оставлять, только то что у нас реализовано и те задачи что покрывает данное приложение.

2023-12-10 05:37 UTC, nocsland commented on PP1/summary_text/docs/README.md
> +Для удобства пользователя добавлен скрипт run.sh, который проверит активировано ли виртуальное окружение,
Скрипт создан не совсем для пользователя. Он скорее для удобства развертывания приложения на сервере.

2023-12-10 05:41 UTC, nocsland requested changes
Поправь пожалуйста.

2023-12-10 20:08 UTC, nocsland approved these changes

2023-12-10 20:10 UTC, merged